### ISSUE TITLE
Make this easy to install

### ISSUE THREAD

**Issue by fgsch** [fgsch/vim-varnish#1]
Use vim-plug or similar so there is no manual fiddling.

**Comment by celesteking** [comment]
doesn't work.
```
Error detected while processing /root/.vimrc:
line    1:
E492: Not an editor command: Plug 'fgsch/vim-varnish'
Press ENTER or type command to continue

#  vim +PlugInstall +qall
Error detected while processing /root/.vimrc:
line    1:
E492: Not an editor command: Plug 'fgsch/vim-varnish'
Press ENTER or type command to continue

```

**Comment by celesteking** [comment]
had to install vim plugin, but now it doesn't highlight anything, plain file as previously.

**Comment by celesteking** [comment]
had to `call plug#end() ` in ~/.vimrc. What a bunch of usability crap.

**Comment by fgsch** [comment]
@celesteking the instructions are provided for a working vim-plug installation, where `plug#end()` is already in place. This follows the format all the other plugin I know of use.  I plan to add instructions for pathogen, which seems to be very common as well, but is out of the scope of the README to provide a step by step installation from scratch, sorry.

That said, if you have any ideas to improve it please let me know.

**Comment by emansom** [comment]
Works for me, using vim-plug.
