### ISSUE TITLE
Tarball releases

### ISSUE THREAD

**Issue by robbat2** [fgsch/vim-varnish#6]
Hi, can you please consider formalized tarball releases, either with semantic versioning, or simple date-based versioning? `YYYYMMDD.N`

This makes it much easier to convey in distribution packaging.

At the bare minimum, just push a tag as the release version, and rely on GitHub's auto tag-to-tarball.

**Comment by fgsch** [comment]
Hi. I haven't so far considered this option because I'm under the impression that most *vim users manage syntax and plugins via a plugin manager, but I can certainly take a look.

**Comment by fgsch** [comment]
I just tagged v0.1.0. Hopefully that will do it, but let me know otherwise.
